config_version: 1

language: en_EN

database:
  type: h2 # Options: mysql, h2
  host: mariadb
  port: 3306
  name: database
  user: username
  password: password

actor_type:
  player:
    start_actions:
      - type: message
        message_key: player_quest.started.message.body
        objective_key: player_quest.started.message.objective
      - type: title
        title_key: player_quest.started.title.title
        subtitle_key: player_quest.started.title.subtitle
      - type: action_bar
        message_key: player_quest.started.action_bar
    progress_actions:
      - type: action_bar
        message_key: player_quest.progress.action_bar
    complete_actions:
      - type: message
        message_key: player_quest.complete.message.body
      - type: title
        title_key: player_quest.complete.title.title
        subtitle_key: player_quest.complete.title.subtitle
  global:
    start_actions:
      - type: message
        message_key: global_quest.started.message.body
        objective_key: global_quest.started.message.objective
      - type: title
        title_key: global_quest.started.title.title
        subtitle_key: global_quest.started.title.subtitle
      - type: action_bar
        message_key: global_quest.started.action_bar
    progress_actions:
      - type: action_bar
        message_key: global_quest.progress.action_bar
    complete_actions:
      - type: message
        message_key: global_quest.complete.message.body
      - type: title
        title_key: global_quest.complete.title.title
        subtitle_key: global_quest.complete.title.subtitle