config-version: 1

language: en_EN

database:
  type: h2 # Options: mysql, h2
  host: mariadb
  port: 3306
  name: database
  user: username
  password: password

player_quest:
  notification:
    start:
      show_action_bar: true
      show_title: true
      show_message: true
    progress:
      show_action_bar: true
    complete:
      show_action_bar: true
      show_title: true
      show_message: true

global_quest:
  notification:
    start:
      show_action_bar: true
      show_title: true
      show_message: true
    progress:
      show_action_bar: true
    complete:
      show_action_bar: true
      show_title: true
      show_message: true